import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Bottom from "@/components/ui/Bottom";
import Nav from "@/components/ui/Nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#E7E7E7]">
        
        {children}
        <Bottom/>
        </body>
    </html>
  );
}
